# Generated by Django 5.1.5 on 2025-01-22 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='user_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
