# Generated by Django 5.1.5 on 2025-01-22 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customuser_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_referrals',
            field=models.ManyToManyField(blank=True, related_name='referral_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
