# Generated by Django 5.1.5 on 2025-01-22 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ManyToManyField(related_name='referred', to=settings.AUTH_USER_MODEL),
        ),
    ]
