# Generated by Django 5.1.5 on 2025-01-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_referral_referred_referral_referred'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
