# Generated by Django 5.1.5 on 2025-01-23 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_delete_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='additional_information',
        ),
        migrations.AddField(
            model_name='kyc',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kyc',
            name='nin_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='kyc',
            name='referral_three_full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='referral_three_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='kyc',
            name='referral_two_full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='referral_two_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
