# Generated by Django 5.1.5 on 2025-01-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_kyc_additional_information_kyc_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_loan_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
