# Generated by Django 5.1.5 on 2025-01-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_customuser_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='referral',
        ),
        migrations.AddField(
            model_name='kyc',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.kyc'),
        ),
    ]
