# Generated by Django 5.1.5 on 2025-01-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_remove_kyc_referral_kyc_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='referred_by',
        ),
    ]
