# Generated by Django 5.1.5 on 2025-01-24 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_kyc_date_approved_kyc_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_referred_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
