# Generated by Django 5.1.5 on 2025-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_kyc_referred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlydue',
            old_name='due_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='monthlydue',
            name='month',
            field=models.CharField(choices=[('jan', 'Jan'), ('feb', 'Feb'), ('mar', 'Mar'), ('apr', 'Apr'), ('may', 'May'), ('jun', 'Jun'), ('jul', 'Jul'), ('aug', 'Aug'), ('sep', 'Sep'), ('oct', 'Oct'), ('nov', 'Nov'), ('dec', 'Dec')], default='jan', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlydue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
