# Generated by Django 5.1.5 on 2025-01-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_rename_due_date_monthlydue_date_monthlydue_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='referral_three_full_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='referral_three_number',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='referral_two_full_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='referral_two_number',
        ),
    ]
