# Generated by Django 5.1.5 on 2025-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_remove_kyc_date_approved_remove_kyc_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
