# Generated by Django 5.1.5 on 2025-01-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_kyc_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='nin_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
